services:
  - type: web
    name: siwesconnect
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        value: siwesconnect-production-secret-2025