from app import create_app
from app.models import db, Organisation

app = create_app()

organisations = [
    # ─── ICT & SOFTWARE ───────────────────────────────────────────────────
    Organisation(name='NITDA', sector='ICT Policy and Regulation', state='FCT', description='National Information Technology Development Agency responsible for IT development policy software systems digital transformation and cybersecurity regulation in Nigeria', relevant_courses='Computer Science, Information Technology, Software Engineering, Cybersecurity, Computer Engineering', opportunity_type='SIWES Placement', website='https://nitda.gov.ng'),
    Organisation(name='NITDA', sector='ICT Policy and Regulation', state='FCT', description='National Information Technology Development Agency responsible for IT development policy software systems digital transformation and cybersecurity regulation in Nigeria', relevant_courses='Computer Science, Information Technology, Software Engineering, Cybersecurity, Computer Engineering', opportunity_type='Graduate Job', website='https://nitda.gov.ng'),

    Organisation(name='Galaxy Backbone', sector='ICT Infrastructure', state='FCT', description='Government ICT infrastructure company providing data centre services cloud computing networking and cybersecurity solutions for federal ministries and agencies', relevant_courses='Computer Science, Computer Engineering, Information Technology, Cybersecurity, Electrical Engineering', opportunity_type='SIWES Placement', website='https://galaxybackbone.com.ng'),
    Organisation(name='Galaxy Backbone', sector='ICT Infrastructure', state='FCT', description='Government ICT infrastructure company providing data centre services cloud computing networking and cybersecurity solutions for federal ministries and agencies', relevant_courses='Computer Science, Computer Engineering, Information Technology, Cybersecurity, Electrical Engineering', opportunity_type='Graduate Job', website='https://galaxybackbone.com.ng'),

    Organisation(name='Nigerian Communications Commission (NCC)', sector='Telecommunications Regulation', state='FCT', description='Federal regulatory authority for the telecommunications industry managing spectrum allocation network licensing and digital infrastructure policy across Nigeria', relevant_courses='Computer Engineering, Electrical Engineering, Computer Science, Information Technology, Law', opportunity_type='SIWES Placement', website='https://ncc.gov.ng'),
    Organisation(name='Nigerian Communications Commission (NCC)', sector='Telecommunications Regulation', state='FCT', description='Federal regulatory authority for the telecommunications industry managing spectrum allocation network licensing and digital infrastructure policy across Nigeria', relevant_courses='Computer Engineering, Electrical Engineering, Computer Science, Information Technology, Law', opportunity_type='Graduate Job', website='https://ncc.gov.ng'),

    Organisation(name='National Identity Management Commission (NIMC)', sector='Digital Identity and ICT', state='FCT', description='Federal agency managing national identity database biometric data capture digital identity systems and NIN registration infrastructure', relevant_courses='Computer Science, Information Technology, Computer Engineering, Cybersecurity', opportunity_type='SIWES Placement', website='https://nimc.gov.ng'),
    Organisation(name='National Identity Management Commission (NIMC)', sector='Digital Identity and ICT', state='FCT', description='Federal agency managing national identity database biometric data capture digital identity systems and NIN registration infrastructure', relevant_courses='Computer Science, Information Technology, Computer Engineering, Cybersecurity', opportunity_type='Graduate Job', website='https://nimc.gov.ng'),

    Organisation(name='Inlaks Computers Nigeria', sector='ICT and Systems Integration', state='FCT', description='Leading technology company providing ICT infrastructure banking automation systems integration networking solutions and IT services to financial institutions and corporations in Nigeria', relevant_courses='Computer Science, Computer Engineering, Information Technology, Electrical Engineering', opportunity_type='SIWES Placement', website='https://inlaks.com'),
    Organisation(name='Inlaks Computers Nigeria', sector='ICT and Systems Integration', state='FCT', description='Leading technology company providing ICT infrastructure banking automation systems integration networking solutions and IT services to financial institutions and corporations in Nigeria', relevant_courses='Computer Science, Computer Engineering, Information Technology, Electrical Engineering', opportunity_type='Graduate Job', website='https://inlaks.com'),

    Organisation(name='Soft Alliance and Resources', sector='Software and ERP Solutions', state='FCT', description='Nigerian software company implementing SAP enterprise resource planning solutions business process automation and IT consulting services for government and private sector clients', relevant_courses='Computer Science, Information Technology, Accounting, Business Administration, Software Engineering', opportunity_type='SIWES Placement', website='https://softalliance.com'),
    Organisation(name='Soft Alliance and Resources', sector='Software and ERP Solutions', state='FCT', description='Nigerian software company implementing SAP enterprise resource planning solutions business process automation and IT consulting services for government and private sector clients', relevant_courses='Computer Science, Information Technology, Accounting, Business Administration, Software Engineering', opportunity_type='Graduate Job', website='https://softalliance.com'),

    Organisation(name='SystemSpecs Nigeria', sector='Fintech and Software', state='FCT', description='Indigenous Nigerian software company developing enterprise financial technology solutions including Remita government payment platform HumanManager HR system and Paylink', relevant_courses='Computer Science, Software Engineering, Information Technology, Accounting, Business Administration', opportunity_type='SIWES Placement', website='https://systemspecs.com.ng'),
    Organisation(name='SystemSpecs Nigeria', sector='Fintech and Software', state='FCT', description='Indigenous Nigerian software company developing enterprise financial technology solutions including Remita government payment platform HumanManager HR system and Paylink', relevant_courses='Computer Science, Software Engineering, Information Technology, Accounting, Business Administration', opportunity_type='Graduate Job', website='https://systemspecs.com.ng'),

    Organisation(name='Infosys Nigeria', sector='IT Consulting and Services', state='FCT', description='Technology consulting and services company providing software development IT outsourcing digital transformation and enterprise solutions to government and corporate clients', relevant_courses='Computer Science, Software Engineering, Information Technology, Computer Engineering', opportunity_type='SIWES Placement', website='https://infosys.com'),
    Organisation(name='Infosys Nigeria', sector='IT Consulting and Services', state='FCT', description='Technology consulting and services company providing software development IT outsourcing digital transformation and enterprise solutions to government and corporate clients', relevant_courses='Computer Science, Software Engineering, Information Technology, Computer Engineering', opportunity_type='Graduate Job', website='https://infosys.com'),

    Organisation(name='Huawei Technologies Nigeria', sector='Telecommunications and ICT', state='FCT', description='Global ICT solutions provider offering telecommunications equipment networking solutions cloud computing and enterprise technology services to Nigerian government and businesses', relevant_courses='Computer Engineering, Electrical Engineering, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://huawei.com/ng'),
    Organisation(name='Huawei Technologies Nigeria', sector='Telecommunications and ICT', state='FCT', description='Global ICT solutions provider offering telecommunications equipment networking solutions cloud computing and enterprise technology services to Nigerian government and businesses', relevant_courses='Computer Engineering, Electrical Engineering, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://huawei.com/ng'),

    Organisation(name='Nile University of Nigeria ICT Directorate', sector='Education and ICT', state='FCT', description='Private university technology department managing campus network systems software development e-learning platforms and digital infrastructure supporting academic operations', relevant_courses='Computer Science, Information Technology, Computer Engineering, Software Engineering', opportunity_type='SIWES Placement', website='https://nileuniversity.edu.ng'),

    Organisation(name='National Space Research and Development Agency (NASRDA)', sector='Space and Technology', state='FCT', description='Federal agency driving space science satellite technology remote sensing geographic information systems and space applications for national development', relevant_courses='Computer Science, Electrical Engineering, Physics, Mathematics, Software Engineering', opportunity_type='SIWES Placement', website='https://nasrda.gov.ng'),
    Organisation(name='National Space Research and Development Agency (NASRDA)', sector='Space and Technology', state='FCT', description='Federal agency driving space science satellite technology remote sensing geographic information systems and space applications for national development', relevant_courses='Computer Science, Electrical Engineering, Physics, Mathematics, Software Engineering', opportunity_type='Graduate Job', website='https://nasrda.gov.ng'),

    Organisation(name='Nigerian Civil Aviation Authority (NCAA)', sector='Aviation and Aerospace', state='FCT', description='Federal regulatory authority for civil aviation in Nigeria managing airspace safety aircraft certification aerodrome standards and aviation security across all Nigerian airports', relevant_courses='Computer Science, Computer Engineering, Electrical Engineering, Mechanical Engineering, Information Technology', opportunity_type='SIWES Placement', website='https://ncaa.gov.ng'),
    Organisation(name='Nigerian Civil Aviation Authority (NCAA)', sector='Aviation and Aerospace', state='FCT', description='Federal regulatory authority for civil aviation in Nigeria managing airspace safety aircraft certification aerodrome standards and aviation security across all Nigerian airports', relevant_courses='Computer Science, Computer Engineering, Electrical Engineering, Mechanical Engineering, Information Technology', opportunity_type='Graduate Job', website='https://ncaa.gov.ng'),

    # ─── TELECOMS ────────────────────────────────────────────────────────
    Organisation(name='MTN Nigeria', sector='Telecommunications', state='FCT', description='Leading telecommunications company in Nigeria offering mobile voice internet connectivity digital financial services and enterprise solutions to millions of subscribers', relevant_courses='Computer Engineering, Electrical Engineering, Computer Science, Information Technology, Business Administration', opportunity_type='SIWES Placement', website='https://mtn.com.ng'),
    Organisation(name='MTN Nigeria', sector='Telecommunications', state='FCT', description='Leading telecommunications company in Nigeria offering mobile voice internet connectivity digital financial services and enterprise solutions to millions of subscribers', relevant_courses='Computer Engineering, Electrical Engineering, Computer Science, Information Technology, Business Administration', opportunity_type='Graduate Job', website='https://mtn.com.ng'),

    Organisation(name='Airtel Nigeria', sector='Telecommunications', state='FCT', description='Major telecommunications operator providing mobile broadband digital services and enterprise connectivity solutions across Nigeria with Abuja as a key operational hub', relevant_courses='Computer Engineering, Electrical Engineering, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://airtel.com.ng'),
    Organisation(name='Airtel Nigeria', sector='Telecommunications', state='FCT', description='Major telecommunications operator providing mobile broadband digital services and enterprise connectivity solutions across Nigeria with Abuja as a key operational hub', relevant_courses='Computer Engineering, Electrical Engineering, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://airtel.com.ng'),

    # ─── BANKING & FINANCE ───────────────────────────────────────────────
    Organisation(name='Central Bank of Nigeria (CBN)', sector='Banking and Finance', state='FCT', description='Apex monetary authority of Nigeria managing monetary policy banking regulation financial system stability currency management and economic research', relevant_courses='Accounting, Economics, Business Administration, Statistics, Mathematics, Computer Science', opportunity_type='SIWES Placement', website='https://cbn.gov.ng'),
    Organisation(name='Central Bank of Nigeria (CBN)', sector='Banking and Finance', state='FCT', description='Apex monetary authority of Nigeria managing monetary policy banking regulation financial system stability currency management and economic research', relevant_courses='Accounting, Economics, Business Administration, Statistics, Mathematics, Computer Science', opportunity_type='Graduate Job', website='https://cbn.gov.ng'),

    Organisation(name='Federal Inland Revenue Service (FIRS)', sector='Taxation and Revenue', state='FCT', description='Federal agency responsible for assessing collecting and accounting for all taxes and revenues accruing to the federal government with ICT accounting law and administrative departments', relevant_courses='Accounting, Economics, Business Administration, Law, Statistics, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://firs.gov.ng'),
    Organisation(name='Federal Inland Revenue Service (FIRS)', sector='Taxation and Revenue', state='FCT', description='Federal agency responsible for assessing collecting and accounting for all taxes and revenues accruing to the federal government with ICT accounting law and administrative departments', relevant_courses='Accounting, Economics, Business Administration, Law, Statistics, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://firs.gov.ng'),

    Organisation(name='Federal Ministry of Finance', sector='Public Finance', state='FCT', description='Government ministry responsible for national budget preparation fiscal policy formulation revenue administration and financial planning for the federation', relevant_courses='Accounting, Economics, Business Administration, Statistics, Computer Science', opportunity_type='SIWES Placement', website='https://finance.gov.ng'),
    Organisation(name='Federal Ministry of Finance', sector='Public Finance', state='FCT', description='Government ministry responsible for national budget preparation fiscal policy formulation revenue administration and financial planning for the federation', relevant_courses='Accounting, Economics, Business Administration, Statistics, Computer Science', opportunity_type='Graduate Job', website='https://finance.gov.ng'),

    Organisation(name='Debt Management Office Nigeria', sector='Public Debt Management', state='FCT', description='Federal agency managing Nigerias domestic and external debt portfolio including issuance of government securities and debt sustainability analysis', relevant_courses='Economics, Accounting, Statistics, Business Administration, Mathematics', opportunity_type='SIWES Placement', website='https://dmo.gov.ng'),
    Organisation(name='Debt Management Office Nigeria', sector='Public Debt Management', state='FCT', description='Federal agency managing Nigerias domestic and external debt portfolio including issuance of government securities and debt sustainability analysis', relevant_courses='Economics, Accounting, Statistics, Business Administration, Mathematics', opportunity_type='Graduate Job', website='https://dmo.gov.ng'),

    Organisation(name='Securities and Exchange Commission (SEC)', sector='Capital Markets Regulation', state='FCT', description='Federal apex regulatory body for the Nigerian capital market overseeing investments securities trading investor protection and financial market development', relevant_courses='Accounting, Economics, Business Administration, Law, Computer Science, Statistics', opportunity_type='SIWES Placement', website='https://sec.gov.ng'),
    Organisation(name='Securities and Exchange Commission (SEC)', sector='Capital Markets Regulation', state='FCT', description='Federal apex regulatory body for the Nigerian capital market overseeing investments securities trading investor protection and financial market development', relevant_courses='Accounting, Economics, Business Administration, Law, Computer Science, Statistics', opportunity_type='Graduate Job', website='https://sec.gov.ng'),

    Organisation(name='National Pension Commission (PenCom)', sector='Pension Regulation', state='FCT', description='Federal regulatory authority supervising pension fund administrators retirement savings accounts and ensuring compliance with the Contributory Pension Scheme across Nigeria', relevant_courses='Accounting, Economics, Business Administration, Law, Computer Science, Statistics', opportunity_type='SIWES Placement', website='https://pencom.gov.ng'),
    Organisation(name='National Pension Commission (PenCom)', sector='Pension Regulation', state='FCT', description='Federal regulatory authority supervising pension fund administrators retirement savings accounts and ensuring compliance with the Contributory Pension Scheme across Nigeria', relevant_courses='Accounting, Economics, Business Administration, Law, Computer Science, Statistics', opportunity_type='Graduate Job', website='https://pencom.gov.ng'),

    Organisation(name='Stanbic IBTC Bank Abuja', sector='Banking', state='FCT', description='Leading financial services group offering personal business and corporate banking investment management insurance and stockbroking services in the Federal Capital Territory', relevant_courses='Accounting, Economics, Business Administration, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://stanbicibtc.com'),
    Organisation(name='Stanbic IBTC Bank Abuja', sector='Banking', state='FCT', description='Leading financial services group offering personal business and corporate banking investment management insurance and stockbroking services in the Federal Capital Territory', relevant_courses='Accounting, Economics, Business Administration, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://stanbicibtc.com'),

    Organisation(name='Guaranty Trust Bank Abuja', sector='Banking', state='FCT', description='Tier one commercial bank offering innovative retail and corporate banking digital financial services and payment solutions with strong technology driven operations', relevant_courses='Accounting, Economics, Business Administration, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://gtbank.com'),
    Organisation(name='Guaranty Trust Bank Abuja', sector='Banking', state='FCT', description='Tier one commercial bank offering innovative retail and corporate banking digital financial services and payment solutions with strong technology driven operations', relevant_courses='Accounting, Economics, Business Administration, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://gtbank.com'),

    Organisation(name='United Bank for Africa (UBA)', sector='Banking', state='FCT', description='Pan-African commercial bank headquartered in Abuja offering retail corporate investment banking digital banking and financial services across 20 African countries', relevant_courses='Accounting, Economics, Business Administration, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://ubagroup.com'),
    Organisation(name='United Bank for Africa (UBA)', sector='Banking', state='FCT', description='Pan-African commercial bank headquartered in Abuja offering retail corporate investment banking digital banking and financial services across 20 African countries', relevant_courses='Accounting, Economics, Business Administration, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://ubagroup.com'),

    Organisation(name='Wapic Insurance Abuja', sector='Insurance', state='FCT', description='Nigerian insurance company providing life general and health insurance products risk management and financial protection services to individuals and corporate clients', relevant_courses='Accounting, Economics, Business Administration, Statistics, Mathematics', opportunity_type='SIWES Placement', website='https://wapic.com'),
    Organisation(name='Wapic Insurance Abuja', sector='Insurance', state='FCT', description='Nigerian insurance company providing life general and health insurance products risk management and financial protection services to individuals and corporate clients', relevant_courses='Accounting, Economics, Business Administration, Statistics, Mathematics', opportunity_type='Graduate Job', website='https://wapic.com'),

    Organisation(name='National Bureau of Statistics (NBS)', sector='Statistics and Research', state='FCT', description='Federal agency responsible for collection compilation analysis publication and dissemination of statistical data on economic social demographic and natural resources in Nigeria', relevant_courses='Statistics, Mathematics, Economics, Computer Science, Information Technology, Business Administration', opportunity_type='SIWES Placement', website='https://nigerianstat.gov.ng'),
    Organisation(name='National Bureau of Statistics (NBS)', sector='Statistics and Research', state='FCT', description='Federal agency responsible for collection compilation analysis publication and dissemination of statistical data on economic social demographic and natural resources in Nigeria', relevant_courses='Statistics, Mathematics, Economics, Computer Science, Information Technology, Business Administration', opportunity_type='Graduate Job', website='https://nigerianstat.gov.ng'),

    Organisation(name='KPMG Nigeria', sector='Audit and Consulting', state='FCT', description='Big Four professional services firm offering audit assurance tax advisory and management consulting services to public sector and private clients across Nigeria', relevant_courses='Accounting, Business Administration, Economics, Law, Statistics, Computer Science', opportunity_type='SIWES Placement', website='https://kpmg.com/ng'),
    Organisation(name='KPMG Nigeria', sector='Audit and Consulting', state='FCT', description='Big Four professional services firm offering audit assurance tax advisory and management consulting services to public sector and private clients across Nigeria', relevant_courses='Accounting, Business Administration, Economics, Law, Statistics, Computer Science', opportunity_type='Graduate Job', website='https://kpmg.com/ng'),

    Organisation(name='PricewaterhouseCoopers Nigeria', sector='Professional Services', state='FCT', description='Leading professional services firm providing assurance tax and advisory services helping organisations solve complex business problems and create value in Nigeria', relevant_courses='Accounting, Business Administration, Economics, Law, Statistics', opportunity_type='SIWES Placement', website='https://pwc.com/ng'),
    Organisation(name='PricewaterhouseCoopers Nigeria', sector='Professional Services', state='FCT', description='Leading professional services firm providing assurance tax and advisory services helping organisations solve complex business problems and create value in Nigeria', relevant_courses='Accounting, Business Administration, Economics, Law, Statistics', opportunity_type='Graduate Job', website='https://pwc.com/ng'),

    Organisation(name='Deloitte Nigeria', sector='Professional Services', state='FCT', description='Global professional services network providing audit consulting financial advisory risk management and tax services to government agencies and corporations in Nigeria', relevant_courses='Accounting, Business Administration, Economics, Law, Statistics, Computer Science', opportunity_type='SIWES Placement', website='https://deloitte.com/ng'),
    Organisation(name='Deloitte Nigeria', sector='Professional Services', state='FCT', description='Global professional services network providing audit consulting financial advisory risk management and tax services to government agencies and corporations in Nigeria', relevant_courses='Accounting, Business Administration, Economics, Law, Statistics, Computer Science', opportunity_type='Graduate Job', website='https://deloitte.com/ng'),

    # ─── ENGINEERING & INFRASTRUCTURE ────────────────────────────────────
    Organisation(name='NNPCL Abuja Headquarters', sector='Oil and Gas', state='FCT', description='Nigerian National Petroleum Company Limited corporate headquarters managing petroleum operations engineering procurement finance human resources and corporate strategy', relevant_courses='Chemical Engineering, Mechanical Engineering, Electrical Engineering, Computer Science, Accounting', opportunity_type='SIWES Placement', website='https://nnpcgroup.com'),
    Organisation(name='NNPCL Abuja Headquarters', sector='Oil and Gas', state='FCT', description='Nigerian National Petroleum Company Limited corporate headquarters managing petroleum operations engineering procurement finance human resources and corporate strategy', relevant_courses='Chemical Engineering, Mechanical Engineering, Electrical Engineering, Computer Science, Accounting', opportunity_type='Graduate Job', website='https://nnpcgroup.com'),

    Organisation(name='Federal Ministry of Works', sector='Civil Engineering and Infrastructure', state='FCT', description='Government ministry responsible for planning design construction and maintenance of federal roads bridges and public infrastructure across Nigeria', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Architecture', opportunity_type='SIWES Placement', website='https://works.gov.ng'),
    Organisation(name='Federal Ministry of Works', sector='Civil Engineering and Infrastructure', state='FCT', description='Government ministry responsible for planning design construction and maintenance of federal roads bridges and public infrastructure across Nigeria', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Architecture', opportunity_type='Graduate Job', website='https://works.gov.ng'),

    Organisation(name='Rural Electrification Agency', sector='Power and Energy', state='FCT', description='Federal agency driving rural electrification through renewable energy mini grids solar systems and off-grid power solutions across underserved Nigerian communities', relevant_courses='Electrical Engineering, Mechanical Engineering, Computer Engineering, Physics', opportunity_type='SIWES Placement', website='https://rea.gov.ng'),
    Organisation(name='Rural Electrification Agency', sector='Power and Energy', state='FCT', description='Federal agency driving rural electrification through renewable energy mini grids solar systems and off-grid power solutions across underserved Nigerian communities', relevant_courses='Electrical Engineering, Mechanical Engineering, Computer Engineering, Physics', opportunity_type='Graduate Job', website='https://rea.gov.ng'),

    Organisation(name='Abuja Electricity Distribution Company (AEDC)', sector='Power Distribution', state='FCT', description='Electric power distribution company serving the Federal Capital Territory and Niger state managing power distribution network customer services and technical operations', relevant_courses='Electrical Engineering, Computer Engineering, Mechanical Engineering, Information Technology', opportunity_type='SIWES Placement', website='https://abujaelectricity.com'),
    Organisation(name='Abuja Electricity Distribution Company (AEDC)', sector='Power Distribution', state='FCT', description='Electric power distribution company serving the Federal Capital Territory and Niger state managing power distribution network customer services and technical operations', relevant_courses='Electrical Engineering, Computer Engineering, Mechanical Engineering, Information Technology', opportunity_type='Graduate Job', website='https://abujaelectricity.com'),

    Organisation(name='Julius Berger Nigeria Abuja', sector='Construction and Engineering', state='FCT', description='Leading construction and engineering company executing major infrastructure projects roads bridges buildings and utilities across Nigeria with headquarters in Abuja', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Architecture, Computer Science', opportunity_type='SIWES Placement', website='https://julius-berger.com'),
    Organisation(name='Julius Berger Nigeria Abuja', sector='Construction and Engineering', state='FCT', description='Leading construction and engineering company executing major infrastructure projects roads bridges buildings and utilities across Nigeria with headquarters in Abuja', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Architecture, Computer Science', opportunity_type='Graduate Job', website='https://julius-berger.com'),

    Organisation(name='Chicason Group', sector='Manufacturing and Construction', state='FCT', description='Diversified Nigerian conglomerate with operations in construction manufacturing real estate and energy providing engineering technical and business support services', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Business Administration, Accounting', opportunity_type='SIWES Placement', website='https://chicasongroup.com'),
    Organisation(name='Chicason Group', sector='Manufacturing and Construction', state='FCT', description='Diversified Nigerian conglomerate with operations in construction manufacturing real estate and energy providing engineering technical and business support services', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Business Administration, Accounting', opportunity_type='Graduate Job', website='https://chicasongroup.com'),

    Organisation(name='Nigerian Ports Authority', sector='Maritime and Ports', state='FCT', description='Federal agency managing Nigerian seaports harbour operations cargo handling maritime safety and port infrastructure with headquarters in Abuja', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Computer Science, Business Administration, Accounting', opportunity_type='SIWES Placement', website='https://nigerianports.gov.ng'),
    Organisation(name='Nigerian Ports Authority', sector='Maritime and Ports', state='FCT', description='Federal agency managing Nigerian seaports harbour operations cargo handling maritime safety and port infrastructure with headquarters in Abuja', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Computer Science, Business Administration, Accounting', opportunity_type='Graduate Job', website='https://nigerianports.gov.ng'),

    Organisation(name='Nigerian Army Corps of Engineers', sector='Military Engineering', state='FCT', description='Engineering arm of the Nigerian Army handling construction infrastructure maintenance civil works and technical operations', relevant_courses='Civil Engineering, Mechanical Engineering, Electrical Engineering, Computer Engineering', opportunity_type='SIWES Placement', website='https://army.mil.ng'),

    Organisation(name='PZ Cussons Nigeria Abuja Office', sector='Consumer Goods', state='FCT', description='Multinational consumer goods company manufacturing and distributing household products personal care items and food products with sales and distribution operations in Abuja', relevant_courses='Chemical Engineering, Business Administration, Accounting, Economics', opportunity_type='SIWES Placement', website='https://pzcussons.com.ng'),
    Organisation(name='PZ Cussons Nigeria Abuja Office', sector='Consumer Goods', state='FCT', description='Multinational consumer goods company manufacturing and distributing household products personal care items and food products with sales and distribution operations in Abuja', relevant_courses='Chemical Engineering, Business Administration, Accounting, Economics', opportunity_type='Graduate Job', website='https://pzcussons.com.ng'),

    Organisation(name='Dangote Group Abuja', sector='Conglomerate', state='FCT', description='Nigerias largest conglomerate with diversified interests in cement production sugar refining flour milling and logistics headquartered in Abuja', relevant_courses='Business Administration, Economics, Accounting, Chemical Engineering, Mechanical Engineering', opportunity_type='SIWES Placement', website='https://dangote.com'),
    Organisation(name='Dangote Group Abuja', sector='Conglomerate', state='FCT', description='Nigerias largest conglomerate with diversified interests in cement production sugar refining flour milling and logistics headquartered in Abuja', relevant_courses='Business Administration, Economics, Accounting, Chemical Engineering, Mechanical Engineering', opportunity_type='Graduate Job', website='https://dangote.com'),

    Organisation(name='Transcorp Abuja', sector='Conglomerate', state='FCT', description='Nigerian conglomerate with interests in energy hospitality and agriculture operating the Transcorp Hilton hotel in Abuja and managing power generation assets', relevant_courses='Business Administration, Economics, Accounting, Electrical Engineering, Mechanical Engineering', opportunity_type='SIWES Placement', website='https://transcorp.com'),
    Organisation(name='Transcorp Abuja', sector='Conglomerate', state='FCT', description='Nigerian conglomerate with interests in energy hospitality and agriculture operating the Transcorp Hilton hotel in Abuja and managing power generation assets', relevant_courses='Business Administration, Economics, Accounting, Electrical Engineering, Mechanical Engineering', opportunity_type='Graduate Job', website='https://transcorp.com'),

    # ─── HEALTH ──────────────────────────────────────────────────────────
    Organisation(name='University of Abuja Teaching Hospital (UATH)', sector='Healthcare', state='FCT', description='Federal tertiary teaching hospital affiliated with University of Abuja providing specialist medical services clinical training and research', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://uath.gov.ng'),
    Organisation(name='University of Abuja Teaching Hospital (UATH)', sector='Healthcare', state='FCT', description='Federal tertiary teaching hospital affiliated with University of Abuja providing specialist medical services clinical training and research', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://uath.gov.ng'),

    Organisation(name='National Hospital Abuja', sector='Healthcare', state='FCT', description='Premier federal tertiary hospital in Abuja providing specialist medical services clinical training research and healthcare administration for the Federal Capital Territory', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://nha.gov.ng'),
    Organisation(name='National Hospital Abuja', sector='Healthcare', state='FCT', description='Premier federal tertiary hospital in Abuja providing specialist medical services clinical training research and healthcare administration for the Federal Capital Territory', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://nha.gov.ng'),

    Organisation(name='NAFDAC', sector='Pharmaceutical Regulation', state='FCT', description='Federal regulatory agency ensuring safety efficacy and quality of food drugs cosmetics medical devices and chemicals manufactured imported or distributed in Nigeria', relevant_courses='Pharmacy, Biochemistry, Chemistry, Microbiology, Medicine and Surgery', opportunity_type='SIWES Placement', website='https://nafdac.gov.ng'),
    Organisation(name='NAFDAC', sector='Pharmaceutical Regulation', state='FCT', description='Federal regulatory agency ensuring safety efficacy and quality of food drugs cosmetics medical devices and chemicals manufactured imported or distributed in Nigeria', relevant_courses='Pharmacy, Biochemistry, Chemistry, Microbiology, Medicine and Surgery', opportunity_type='Graduate Job', website='https://nafdac.gov.ng'),

    Organisation(name='Federal Ministry of Health', sector='Public Health', state='FCT', description='Government ministry coordinating national health policy programmes disease control health infrastructure and medical research across Nigeria', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry', opportunity_type='SIWES Placement', website='https://health.gov.ng'),
    Organisation(name='Federal Ministry of Health', sector='Public Health', state='FCT', description='Government ministry coordinating national health policy programmes disease control health infrastructure and medical research across Nigeria', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry', opportunity_type='Graduate Job', website='https://health.gov.ng'),

    Organisation(name='Garki Hospital Abuja', sector='Healthcare', state='FCT', description='FCT government general hospital providing comprehensive healthcare services to residents of Abuja', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://fct.gov.ng'),
    Organisation(name='Garki Hospital Abuja', sector='Healthcare', state='FCT', description='FCT government general hospital providing comprehensive healthcare services to residents of Abuja', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://fct.gov.ng'),

    Organisation(name='Wuse General Hospital', sector='Healthcare', state='FCT', description='FCT government hospital serving Wuse and central Abuja providing medical surgical and outpatient services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://fct.gov.ng'),
    Organisation(name='Wuse General Hospital', sector='Healthcare', state='FCT', description='FCT government hospital serving Wuse and central Abuja providing medical surgical and outpatient services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://fct.gov.ng'),

    Organisation(name='Gwagwalada Specialist Hospital', sector='Healthcare', state='FCT', description='FCT specialist hospital serving Gwagwalada area council providing medical surgical maternity and specialist services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://fct.gov.ng'),
    Organisation(name='Gwagwalada Specialist Hospital', sector='Healthcare', state='FCT', description='FCT specialist hospital serving Gwagwalada area council providing medical surgical maternity and specialist services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://fct.gov.ng'),

    Organisation(name='Kubwa General Hospital', sector='Healthcare', state='FCT', description='FCT government hospital serving Kubwa and Bwari area councils providing general medical services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://fct.gov.ng'),
    Organisation(name='Kubwa General Hospital', sector='Healthcare', state='FCT', description='FCT government hospital serving Kubwa and Bwari area councils providing general medical services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://fct.gov.ng'),

    Organisation(name='Maitama District Hospital', sector='Healthcare', state='FCT', description='FCT government district hospital in Maitama providing specialist and general medical services to Abuja residents', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://fct.gov.ng'),
    Organisation(name='Maitama District Hospital', sector='Healthcare', state='FCT', description='FCT government district hospital in Maitama providing specialist and general medical services to Abuja residents', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://fct.gov.ng'),

    Organisation(name='Cedarcrest Hospitals Abuja', sector='Private Healthcare', state='FCT', description='Leading private specialist hospital in Abuja providing cardiology oncology maternity and surgical services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://cedarcresthospitals.com'),
    Organisation(name='Cedarcrest Hospitals Abuja', sector='Private Healthcare', state='FCT', description='Leading private specialist hospital in Abuja providing cardiology oncology maternity and surgical services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://cedarcresthospitals.com'),

    Organisation(name='Nisa Premier Hospital Abuja', sector='Private Healthcare', state='FCT', description='Private hospital in Abuja providing comprehensive medical services including maternity surgery and specialist care', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://nisahospital.com'),
    Organisation(name='Nisa Premier Hospital Abuja', sector='Private Healthcare', state='FCT', description='Private hospital in Abuja providing comprehensive medical services including maternity surgery and specialist care', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://nisahospital.com'),

    Organisation(name='Abuja Clinics', sector='Private Healthcare', state='FCT', description='Leading private hospital group in Abuja providing comprehensive medical services specialist care laboratory pharmacy and diagnostic services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://abujaclinics.com'),
    Organisation(name='Abuja Clinics', sector='Private Healthcare', state='FCT', description='Leading private hospital group in Abuja providing comprehensive medical services specialist care laboratory pharmacy and diagnostic services', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://abujaclinics.com'),

    Organisation(name='FCT Primary Healthcare Development Agency', sector='Public Health', state='FCT', description='FCT government agency coordinating primary healthcare delivery across all six area councils managing health centres community health workers and disease prevention programmes', relevant_courses='Medicine and Surgery, Nursing Science, Biochemistry, Microbiology, Business Administration', opportunity_type='SIWES Placement', website='https://fct.gov.ng'),
    Organisation(name='FCT Primary Healthcare Development Agency', sector='Public Health', state='FCT', description='FCT government agency coordinating primary healthcare delivery across all six area councils managing health centres community health workers and disease prevention programmes', relevant_courses='Medicine and Surgery, Nursing Science, Biochemistry, Microbiology, Business Administration', opportunity_type='Graduate Job', website='https://fct.gov.ng'),

    Organisation(name='Nigerian Air Force Hospital Abuja', sector='Military Healthcare', state='FCT', description='Military hospital providing healthcare services to Nigerian Air Force personnel and their families in Abuja', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='SIWES Placement', website='https://airforce.mil.ng'),
    Organisation(name='Nigerian Air Force Hospital Abuja', sector='Military Healthcare', state='FCT', description='Military hospital providing healthcare services to Nigerian Air Force personnel and their families in Abuja', relevant_courses='Medicine and Surgery, Pharmacy, Nursing Science, Biochemistry, Microbiology', opportunity_type='Graduate Job', website='https://airforce.mil.ng'),

    # ─── MEDIA & COMMUNICATION ───────────────────────────────────────────
    Organisation(name='Nigerian Television Authority (NTA)', sector='Broadcasting and Media', state='FCT', description='Federal government broadcasting corporation operating television stations across all states producing news current affairs entertainment and educational content', relevant_courses='Mass Communication, Information Technology, Computer Science, Electrical Engineering', opportunity_type='SIWES Placement', website='https://nta.gov.ng'),
    Organisation(name='Nigerian Television Authority (NTA)', sector='Broadcasting and Media', state='FCT', description='Federal government broadcasting corporation operating television stations across all states producing news current affairs entertainment and educational content', relevant_courses='Mass Communication, Information Technology, Computer Science, Electrical Engineering', opportunity_type='Graduate Job', website='https://nta.gov.ng'),

    Organisation(name='Voice of Nigeria', sector='Broadcasting and Media', state='FCT', description='Nigeria international broadcasting service producing radio programmes in multiple languages for domestic and international audiences under the Ministry of Information', relevant_courses='Mass Communication', opportunity_type='SIWES Placement', website='https://von.gov.ng'),
    Organisation(name='Voice of Nigeria', sector='Broadcasting and Media', state='FCT', description='Nigeria international broadcasting service producing radio programmes in multiple languages for domestic and international audiences under the Ministry of Information', relevant_courses='Mass Communication', opportunity_type='Graduate Job', website='https://von.gov.ng'),

    Organisation(name='National Orientation Agency', sector='Public Communication', state='FCT', description='Federal agency responsible for civic education national orientation public enlightenment and communication of government policies and programmes to Nigerians', relevant_courses='Mass Communication, Business Administration', opportunity_type='SIWES Placement', website='https://noa.gov.ng'),
    Organisation(name='National Orientation Agency', sector='Public Communication', state='FCT', description='Federal agency responsible for civic education national orientation public enlightenment and communication of government policies and programmes to Nigerians', relevant_courses='Mass Communication, Business Administration', opportunity_type='Graduate Job', website='https://noa.gov.ng'),

    Organisation(name='Channels Television Abuja', sector='Media and Broadcasting', state='FCT', description='Leading independent television broadcaster in Nigeria known for news current affairs investigative journalism and political programmes with headquarters in Abuja', relevant_courses='Mass Communication, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://channelstv.com'),
    Organisation(name='Channels Television Abuja', sector='Media and Broadcasting', state='FCT', description='Leading independent television broadcaster in Nigeria known for news current affairs investigative journalism and political programmes with headquarters in Abuja', relevant_courses='Mass Communication, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://channelstv.com'),

    # ─── AGRICULTURE ─────────────────────────────────────────────────────
    Organisation(name='Federal Ministry of Agriculture', sector='Agriculture', state='FCT', description='Government ministry responsible for agricultural policy food security livestock fisheries extension services and rural development programmes across Nigeria', relevant_courses='Agricultural Science, Chemistry, Biochemistry, Business Administration, Economics', opportunity_type='SIWES Placement', website='https://fmard.gov.ng'),
    Organisation(name='Federal Ministry of Agriculture', sector='Agriculture', state='FCT', description='Government ministry responsible for agricultural policy food security livestock fisheries extension services and rural development programmes across Nigeria', relevant_courses='Agricultural Science, Chemistry, Biochemistry, Business Administration, Economics', opportunity_type='Graduate Job', website='https://fmard.gov.ng'),

    Organisation(name='National Agricultural Development Fund', sector='Agricultural Finance', state='FCT', description='Federal fund providing financial support technical assistance and capacity building for agricultural development value chain financing and agribusiness growth in Nigeria', relevant_courses='Agricultural Science, Economics, Accounting, Business Administration', opportunity_type='SIWES Placement', website='https://nadf.gov.ng'),
    Organisation(name='National Agricultural Development Fund', sector='Agricultural Finance', state='FCT', description='Federal fund providing financial support technical assistance and capacity building for agricultural development value chain financing and agribusiness growth in Nigeria', relevant_courses='Agricultural Science, Economics, Accounting, Business Administration', opportunity_type='Graduate Job', website='https://nadf.gov.ng'),

    Organisation(name='Nigerian Meteorological Agency (NiMet)', sector='Science and Research', state='FCT', description='Federal agency providing meteorological services weather forecasting climate monitoring atmospheric research and environmental data for aviation agriculture and disaster management', relevant_courses='Physics, Computer Science, Mathematics, Statistics, Electrical Engineering', opportunity_type='SIWES Placement', website='https://nimet.gov.ng'),
    Organisation(name='Nigerian Meteorological Agency (NiMet)', sector='Science and Research', state='FCT', description='Federal agency providing meteorological services weather forecasting climate monitoring atmospheric research and environmental data for aviation agriculture and disaster management', relevant_courses='Physics, Computer Science, Mathematics, Statistics, Electrical Engineering', opportunity_type='Graduate Job', website='https://nimet.gov.ng'),

    # ─── LAW & ADMINISTRATION ─────────────────────────────────────────────
    Organisation(name='Federal Ministry of Justice', sector='Legal and Justice', state='FCT', description='Government ministry responsible for legal advice to government prosecution of federal offences law reform treaty negotiation and administration of justice in Nigeria', relevant_courses='Law', opportunity_type='SIWES Placement', website='https://justice.gov.ng'),
    Organisation(name='Federal Ministry of Justice', sector='Legal and Justice', state='FCT', description='Government ministry responsible for legal advice to government prosecution of federal offences law reform treaty negotiation and administration of justice in Nigeria', relevant_courses='Law', opportunity_type='Graduate Job', website='https://justice.gov.ng'),

    Organisation(name='National Judicial Council', sector='Judiciary', state='FCT', description='Constitutional body responsible for managing the federal judiciary recommending judicial appointments and maintaining standards of judicial conduct in Nigeria', relevant_courses='Law', opportunity_type='SIWES Placement', website='https://njc.gov.ng'),
    Organisation(name='National Judicial Council', sector='Judiciary', state='FCT', description='Constitutional body responsible for managing the federal judiciary recommending judicial appointments and maintaining standards of judicial conduct in Nigeria', relevant_courses='Law', opportunity_type='Graduate Job', website='https://njc.gov.ng'),

    Organisation(name='Corporate Affairs Commission (CAC)', sector='Business Registration and Regulation', state='FCT', description='Federal agency responsible for companies and business names registration regulation and administration of company law in Nigeria', relevant_courses='Law, Accounting, Business Administration, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://cac.gov.ng'),
    Organisation(name='Corporate Affairs Commission (CAC)', sector='Business Registration and Regulation', state='FCT', description='Federal agency responsible for companies and business names registration regulation and administration of company law in Nigeria', relevant_courses='Law, Accounting, Business Administration, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://cac.gov.ng'),

    Organisation(name='Economic and Financial Crimes Commission (EFCC)', sector='Law Enforcement and Anti-Corruption', state='FCT', description='Federal agency investigating and prosecuting financial crimes money laundering advance fee fraud and economic crimes with forensic ICT and legal units in Abuja', relevant_courses='Law, Accounting, Computer Science, Information Technology, Economics', opportunity_type='SIWES Placement', website='https://efcc.gov.ng'),
    Organisation(name='Economic and Financial Crimes Commission (EFCC)', sector='Law Enforcement and Anti-Corruption', state='FCT', description='Federal agency investigating and prosecuting financial crimes money laundering advance fee fraud and economic crimes with forensic ICT and legal units in Abuja', relevant_courses='Law, Accounting, Computer Science, Information Technology, Economics', opportunity_type='Graduate Job', website='https://efcc.gov.ng'),

    Organisation(name='Nigerian Copyright Commission', sector='Intellectual Property', state='FCT', description='Federal agency administering copyright law protecting intellectual property rights enforcing anti-piracy measures and promoting creative industries in Nigeria', relevant_courses='Law, Mass Communication, Computer Science, Business Administration', opportunity_type='SIWES Placement', website='https://copyright.gov.ng'),
    Organisation(name='Nigerian Copyright Commission', sector='Intellectual Property', state='FCT', description='Federal agency administering copyright law protecting intellectual property rights enforcing anti-piracy measures and promoting creative industries in Nigeria', relevant_courses='Law, Mass Communication, Computer Science, Business Administration', opportunity_type='Graduate Job', website='https://copyright.gov.ng'),

    Organisation(name='Nigeria Customs Service', sector='Trade and Revenue', state='FCT', description='Federal agency responsible for border control trade facilitation revenue collection import and export regulation with ICT finance and legal departments at headquarters in Abuja', relevant_courses='Accounting, Economics, Business Administration, Law, Computer Science, Information Technology', opportunity_type='SIWES Placement', website='https://customs.gov.ng'),
    Organisation(name='Nigeria Customs Service', sector='Trade and Revenue', state='FCT', description='Federal agency responsible for border control trade facilitation revenue collection import and export regulation with ICT finance and legal departments at headquarters in Abuja', relevant_courses='Accounting, Economics, Business Administration, Law, Computer Science, Information Technology', opportunity_type='Graduate Job', website='https://customs.gov.ng'),

    Organisation(name='Nigeria Immigration Service', sector='Immigration and Border Management', state='FCT', description='Federal agency managing immigration control passport issuance visa processing border management and expatriate quota administration with ICT and administrative units in Abuja', relevant_courses='Computer Science, Information Technology, Business Administration, Law, Accounting', opportunity_type='SIWES Placement', website='https://immigration.gov.ng'),
    Organisation(name='Nigeria Immigration Service', sector='Immigration and Border Management', state='FCT', description='Federal agency managing immigration control passport issuance visa processing border management and expatriate quota administration with ICT and administrative units in Abuja', relevant_courses='Computer Science, Information Technology, Business Administration, Law, Accounting', opportunity_type='Graduate Job', website='https://immigration.gov.ng'),

    Organisation(name='Nigeria Police Force Headquarters', sector='Law Enforcement', state='FCT', description='Federal law enforcement agency headquarters in Abuja coordinating policing operations criminal investigations forensic services ICT systems and administrative functions nationwide', relevant_courses='Computer Science, Information Technology, Law, Business Administration', opportunity_type='SIWES Placement', website='https://npf.gov.ng'),
    Organisation(name='Nigeria Police Force Headquarters', sector='Law Enforcement', state='FCT', description='Federal law enforcement agency headquarters in Abuja coordinating policing operations criminal investigations forensic services ICT systems and administrative functions nationwide', relevant_courses='Computer Science, Information Technology, Law, Business Administration', opportunity_type='Graduate Job', website='https://npf.gov.ng'),

    Organisation(name='Independent National Electoral Commission (INEC)', sector='Electoral Administration', state='FCT', description='Federal agency responsible for conducting elections voter registration result collation and electoral administration with strong ICT data management and legal departments in Abuja', relevant_courses='Computer Science, Information Technology, Law, Business Administration, Statistics, Mathematics', opportunity_type='SIWES Placement', website='https://inec.gov.ng'),
    Organisation(name='Independent National Electoral Commission (INEC)', sector='Electoral Administration', state='FCT', description='Federal agency responsible for conducting elections voter registration result collation and electoral administration with strong ICT data management and legal departments in Abuja', relevant_courses='Computer Science, Information Technology, Law, Business Administration, Statistics, Mathematics', opportunity_type='Graduate Job', website='https://inec.gov.ng'),

    Organisation(name='Abuja Municipal Area Council (AMAC)', sector='Local Government Administration', state='FCT', description='Local government authority managing urban administration revenue collection community development public works and social services within the Abuja Municipal Area Council', relevant_courses='Business Administration, Accounting, Law, Computer Science, Mass Communication', opportunity_type='SIWES Placement', website='https://amac.gov.ng'),
    Organisation(name='Abuja Municipal Area Council (AMAC)', sector='Local Government Administration', state='FCT', description='Local government authority managing urban administration revenue collection community development public works and social services within the Abuja Municipal Area Council', relevant_courses='Business Administration, Accounting, Law, Computer Science, Mass Communication', opportunity_type='Graduate Job', website='https://amac.gov.ng'),

    Organisation(name='Federal Road Safety Corps (FRSC)', sector='Road Safety and Transport', state='FCT', description='Federal agency responsible for road safety management vehicle inspection driver licensing traffic regulations and accident prevention across Nigeria with headquarters in Abuja', relevant_courses='Computer Science, Information Technology, Mechanical Engineering, Business Administration, Law', opportunity_type='SIWES Placement', website='https://frsc.gov.ng'),
    Organisation(name='Federal Road Safety Corps (FRSC)', sector='Road Safety and Transport', state='FCT', description='Federal agency responsible for road safety management vehicle inspection driver licensing traffic regulations and accident prevention across Nigeria with headquarters in Abuja', relevant_courses='Computer Science, Information Technology, Mechanical Engineering, Business Administration, Law', opportunity_type='Graduate Job', website='https://frsc.gov.ng'),

    Organisation(name='Aluko and Oyebode Law Firm', sector='Legal Services', state='FCT', description='One of Nigerias foremost commercial law firms offering corporate finance mergers and acquisitions energy law dispute resolution and regulatory advisory services', relevant_courses='Law', opportunity_type='SIWES Placement', website='https://aluko-oyebode.com'),
    Organisation(name='Aluko and Oyebode Law Firm', sector='Legal Services', state='FCT', description='One of Nigerias foremost commercial law firms offering corporate finance mergers and acquisitions energy law dispute resolution and regulatory advisory services', relevant_courses='Law', opportunity_type='Graduate Job', website='https://aluko-oyebode.com'),

    Organisation(name='Udo Udoma and Belo-Osagie', sector='Legal Services', state='FCT', description='Top tier Nigerian law firm providing comprehensive legal services in corporate law banking finance energy and natural resources and dispute resolution', relevant_courses='Law', opportunity_type='SIWES Placement', website='https://uubo.org'),
    Organisation(name='Udo Udoma and Belo-Osagie', sector='Legal Services', state='FCT', description='Top tier Nigerian law firm providing comprehensive legal services in corporate law banking finance energy and natural resources and dispute resolution', relevant_courses='Law', opportunity_type='Graduate Job', website='https://uubo.org'),

    Organisation(name='Templars Law Firm', sector='Legal Services', state='FCT', description='Leading full service Nigerian law firm providing corporate commercial dispute resolution energy and natural resources and regulatory legal services to major clients in Abuja', relevant_courses='Law', opportunity_type='SIWES Placement', website='https://templars-law.com'),
    Organisation(name='Templars Law Firm', sector='Legal Services', state='FCT', description='Leading full service Nigerian law firm providing corporate commercial dispute resolution energy and natural resources and regulatory legal services to major clients in Abuja', relevant_courses='Law', opportunity_type='Graduate Job', website='https://templars-law.com'),
]

